#pragma once

#include <array>
#include <cstdint>
#include <string>

namespace survival
{
	struct record_t
	{
		std::uint8_t tier;
		std::uint8_t category; // 0 weapon 1 ammo 2 heal 3 gear 4 attachment 5 grenade 6 misc
		const char* name;
	};

	inline constexpr std::array<record_t, 428> k_records{{
		{ 0, 6, "" },
		{ 5, 0, "Kraber" },
		{ 1, 0, "Mastiff" },
		{ 1, 0, "Mastiff" },
		{ 2, 0, "Mastiff" },
		{ 3, 0, "Mastiff" },
		{ 4, 0, "Mastiff" },
		{ 5, 0, "Mastiff" },
		{ 1, 0, "L-STAR" },
		{ 5, 0, "L-STAR" },
		{ 1, 0, "L-STAR" },
		{ 2, 0, "L-STAR" },
		{ 3, 0, "L-STAR" },
		{ 4, 0, "L-STAR" },
		{ 1, 0, "HAVOC" },
		{ 1, 0, "HAVOC" },
		{ 2, 0, "HAVOC" },
		{ 3, 0, "HAVOC" },
		{ 4, 0, "HAVOC" },
		{ 5, 0, "HAVOC" },
		{ 1, 0, "Devotion" },
		{ 5, 0, "Devotion" },
		{ 1, 0, "Devotion" },
		{ 2, 0, "Devotion" },
		{ 3, 0, "Devotion" },
		{ 4, 0, "Devotion" },
		{ 1, 0, "Triple Take" },
		{ 5, 0, "Triple Take" },
		{ 1, 0, "Triple Take" },
		{ 2, 0, "Triple Take" },
		{ 3, 0, "Triple Take" },
		{ 4, 0, "Triple Take" },
		{ 1, 0, "Flatline" },
		{ 5, 0, "Flatline" },
		{ 1, 0, "Flatline" },
		{ 2, 0, "Flatline" },
		{ 3, 0, "Flatline" },
		{ 4, 0, "Flatline" },
		{ 1, 0, "Hemlok" },
		{ 5, 0, "Hemlok" },
		{ 1, 0, "Hemlok" },
		{ 2, 0, "Hemlok" },
		{ 3, 0, "Hemlok" },
		{ 4, 0, "Hemlok" },
		{ 1, 0, "Hemlok Breach" },
		{ 5, 0, "Hemlok Breach" },
		{ 1, 0, "Hemlok Breach" },
		{ 2, 0, "Hemlok Breach" },
		{ 3, 0, "Hemlok Breach" },
		{ 4, 0, "Hemlok Breach" },
		{ 1, 0, "G7 Scout" },
		{ 5, 0, "G7 Scout" },
		{ 1, 0, "G7 Scout" },
		{ 2, 0, "G7 Scout" },
		{ 3, 0, "G7 Scout" },
		{ 4, 0, "G7 Scout" },
		{ 1, 0, "Alternator" },
		{ 5, 0, "Alternator" },
		{ 1, 0, "Alternator" },
		{ 2, 0, "Alternator" },
		{ 3, 0, "Alternator" },
		{ 4, 0, "Alternator" },
		{ 1, 0, "R-99" },
		{ 1, 0, "R-99" },
		{ 2, 0, "R-99" },
		{ 3, 0, "R-99" },
		{ 4, 0, "R-99" },
		{ 5, 0, "R-99" },
		{ 1, 0, "Prowler" },
		{ 5, 0, "Prowler" },
		{ 1, 0, "Prowler" },
		{ 2, 0, "Prowler" },
		{ 3, 0, "Prowler" },
		{ 4, 0, "Prowler" },
		{ 1, 0, "Volt" },
		{ 5, 0, "Volt" },
		{ 1, 0, "Volt" },
		{ 2, 0, "Volt" },
		{ 3, 0, "Volt" },
		{ 4, 0, "Volt" },
		{ 1, 0, "Longbow" },
		{ 5, 0, "Longbow" },
		{ 1, 0, "Longbow" },
		{ 2, 0, "Longbow" },
		{ 3, 0, "Longbow" },
		{ 4, 0, "Longbow" },
		{ 1, 0, "Charge Rifle" },
		{ 5, 0, "Charge Rifle" },
		{ 1, 0, "Charge Rifle" },
		{ 2, 0, "Charge Rifle" },
		{ 3, 0, "Charge Rifle" },
		{ 4, 0, "Charge Rifle" },
		{ 1, 0, "Spitfire" },
		{ 5, 0, "Spitfire" },
		{ 1, 0, "Spitfire" },
		{ 2, 0, "Spitfire" },
		{ 3, 0, "Spitfire" },
		{ 4, 0, "Spitfire" },
		{ 1, 0, "R-301" },
		{ 5, 0, "R-301" },
		{ 1, 0, "R-301" },
		{ 2, 0, "R-301" },
		{ 3, 0, "R-301" },
		{ 4, 0, "R-301" },
		{ 1, 0, "EVA-8" },
		{ 5, 0, "EVA-8" },
		{ 1, 0, "EVA-8" },
		{ 2, 0, "EVA-8" },
		{ 3, 0, "EVA-8" },
		{ 4, 0, "EVA-8" },
		{ 1, 0, "Peacekeeper" },
		{ 5, 0, "Peacekeeper" },
		{ 1, 0, "Peacekeeper" },
		{ 2, 0, "Peacekeeper" },
		{ 3, 0, "Peacekeeper" },
		{ 4, 0, "Peacekeeper" },
		{ 1, 0, "Mozambique" },
		{ 1, 0, "Mozambique" },
		{ 2, 0, "Mozambique" },
		{ 3, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 5, 0, "Mozambique" },
		{ 5, 0, "Mozambique" },
		{ 1, 0, "Mozambique" },
		{ 2, 0, "Mozambique" },
		{ 3, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 4, 0, "Mozambique" },
		{ 1, 0, "Wingman" },
		{ 5, 0, "Wingman" },
		{ 1, 0, "Wingman" },
		{ 2, 0, "Wingman" },
		{ 3, 0, "Wingman" },
		{ 4, 0, "Wingman" },
		{ 1, 0, "P2020" },
		{ 1, 0, "P2020" },
		{ 2, 0, "P2020" },
		{ 3, 0, "P2020" },
		{ 4, 0, "P2020" },
		{ 5, 0, "P2020" },
		{ 5, 0, "P2020" },
		{ 1, 0, "P2020" },
		{ 2, 0, "P2020" },
		{ 3, 0, "P2020" },
		{ 4, 0, "P2020" },
		{ 1, 0, "RE-45" },
		{ 5, 0, "RE-45" },
		{ 1, 0, "RE-45 Burst" },
		{ 5, 0, "RE-45 Burst" },
		{ 1, 0, "RE-45 Burst" },
		{ 2, 0, "RE-45 Burst" },
		{ 3, 0, "RE-45 Burst" },
		{ 4, 0, "RE-45 Burst" },
		{ 1, 0, "RE-45" },
		{ 2, 0, "RE-45" },
		{ 3, 0, "RE-45" },
		{ 4, 0, "RE-45" },
		{ 1, 0, "Sentinel" },
		{ 5, 0, "Sentinel" },
		{ 1, 0, "Sentinel" },
		{ 2, 0, "Sentinel" },
		{ 3, 0, "Sentinel" },
		{ 4, 0, "Sentinel" },
		{ 5, 0, "EPG" },
		{ 5, 0, "EPG" },
		{ 1, 0, "Bocek" },
		{ 5, 0, "Bocek" },
		{ 5, 0, "Bocek" },
		{ 1, 0, "Bocek" },
		{ 2, 0, "Bocek" },
		{ 3, 0, "Bocek" },
		{ 4, 0, "Bocek" },
		{ 5, 0, "30-30" },
		{ 1, 0, "30-30" },
		{ 1, 0, "30-30" },
		{ 2, 0, "30-30" },
		{ 3, 0, "30-30" },
		{ 4, 0, "30-30" },
		{ 1, 0, "Nemesis" },
		{ 5, 0, "Nemesis" },
		{ 1, 0, "Nemesis" },
		{ 2, 0, "Nemesis" },
		{ 3, 0, "Nemesis" },
		{ 4, 0, "Nemesis" },
		{ 1, 1, "Light Ammo" },
		{ 1, 1, "Energy Ammo" },
		{ 1, 1, "Shotgun Ammo" },
		{ 1, 1, "Heavy Ammo" },
		{ 1, 1, "Sniper Ammo" },
		{ 1, 1, "Arrows" },
		{ 1, 1, "Arrow Bundle" },
		{ 1, 0, "Rampage" },
		{ 5, 0, "Rampage" },
		{ 1, 0, "Rampage" },
		{ 2, 0, "Rampage" },
		{ 3, 0, "Rampage" },
		{ 4, 0, "Rampage" },
		{ 1, 0, "C.A.R." },
		{ 5, 0, "C.A.R." },
		{ 1, 0, "C.A.R." },
		{ 2, 0, "C.A.R." },
		{ 3, 0, "C.A.R." },
		{ 4, 0, "C.A.R." },
		{ 2, 0, "P2020" },
		{ 2, 0, "Mozambique" },
		{ 2, 0, "Alternator" },
		{ 2, 0, "G7 Scout" },
		{ 2, 0, "Hemlok" },
		{ 2, 0, "R-99" },
		{ 2, 0, "Mastiff" },
		{ 2, 0, "30-30" },
		{ 3, 0, "RE-45" },
		{ 3, 0, "30-30" },
		{ 3, 0, "Wingman" },
		{ 3, 0, "EVA-8" },
		{ 3, 0, "Spitfire" },
		{ 3, 0, "Rampage" },
		{ 3, 0, "Flatline" },
		{ 3, 0, "Prowler" },
		{ 3, 0, "Longbow" },
		{ 4, 0, "30-30" },
		{ 4, 0, "Rampage" },
		{ 4, 0, "RE-45" },
		{ 4, 0, "P2020" },
		{ 4, 0, "Mozambique" },
		{ 4, 0, "Wingman" },
		{ 4, 0, "EVA-8" },
		{ 4, 0, "Mastiff" },
		{ 4, 0, "Prowler" },
		{ 4, 0, "R-99" },
		{ 4, 0, "Flatline" },
		{ 4, 0, "Hemlok" },
		{ 4, 0, "R-301" },
		{ 4, 0, "G7 Scout" },
		{ 4, 0, "Longbow" },
		{ 3, 2, "Ult Accel" },
		{ 3, 2, "Phoenix Kit" },
		{ 2, 2, "Med Kit" },
		{ 1, 2, "Syringe" },
		{ 2, 2, "Shield Battery" },
		{ 1, 2, "Shield Cell" },
		{ 1, 3, "Helmet" },
		{ 2, 3, "Helmet" },
		{ 3, 3, "Helmet" },
		{ 4, 3, "Helmet" },
		{ 4, 3, "Gold Helmet" },
		{ 5, 3, "Mythic Helmet" },
		{ 5, 3, "Sunglasses" },
		{ 0, 3, "Body Shield" },
		{ 1, 3, "Body Shield" },
		{ 2, 3, "Body Shield" },
		{ 3, 3, "Body Shield" },
		{ 4, 3, "Body Shield" },
		{ 0, 3, "Evo Shield" },
		{ 1, 3, "Evo Shield" },
		{ 2, 3, "Evo Shield" },
		{ 3, 3, "Evo Shield" },
		{ 5, 3, "Evo Shield" },
		{ 1, 3, "Shield Core" },
		{ 2, 3, "Shield Core" },
		{ 3, 3, "Shield Core" },
		{ 5, 3, "Shield Core" },
		{ 0, 3, "Knockdown Shield" },
		{ 1, 3, "Knockdown Shield" },
		{ 2, 3, "Knockdown Shield" },
		{ 3, 3, "Knockdown Shield" },
		{ 4, 3, "Knockdown Shield" },
		{ 1, 3, "Backpack" },
		{ 2, 3, "Backpack" },
		{ 3, 3, "Backpack" },
		{ 4, 3, "Backpack" },
		{ 5, 0, "Throwing Knife" },
		{ 1, 5, "Thermite" },
		{ 1, 5, "Frag" },
		{ 1, 5, "Arc Star" },
		{ 1, 4, "1x HCOG" },
		{ 2, 4, "2x HCOG" },
		{ 1, 4, "1x Holo" },
		{ 2, 4, "1x-2x Holo" },
		{ 4, 4, "1x Digi Threat" },
		{ 3, 4, "3x HCOG" },
		{ 3, 4, "2x-4x AOG" },
		{ 2, 4, "6x Sniper" },
		{ 3, 4, "4x-8x Sniper" },
		{ 4, 4, "4x-10x Digi" },
		{ 1, 4, "Barrel Stabilizer" },
		{ 2, 4, "Barrel Stabilizer" },
		{ 3, 4, "Barrel Stabilizer" },
		{ 1, 4, "Hemlok Elite Barrel" },
		{ 1, 4, "Laser Sight" },
		{ 2, 4, "Laser Sight" },
		{ 3, 4, "Laser Sight" },
		{ 4, 4, "Laser Sight" },
		{ 1, 4, "Light Mag" },
		{ 2, 4, "Light Mag" },
		{ 3, 4, "Light Mag" },
		{ 4, 4, "Light Mag" },
		{ 1, 4, "Heavy Mag" },
		{ 2, 4, "Heavy Mag" },
		{ 3, 4, "Heavy Mag" },
		{ 4, 4, "Heavy Mag" },
		{ 1, 4, "Energy Mag" },
		{ 2, 4, "Energy Mag" },
		{ 3, 4, "Energy Mag" },
		{ 4, 4, "Energy Mag" },
		{ 1, 4, "Sniper Mag" },
		{ 2, 4, "Sniper Mag" },
		{ 3, 4, "Sniper Mag" },
		{ 4, 4, "Sniper Mag" },
		{ 1, 4, "Shotgun Bolt" },
		{ 2, 4, "Shotgun Bolt" },
		{ 3, 4, "Shotgun Bolt" },
		{ 4, 4, "Shotgun Bolt" },
		{ 1, 4, "Standard Stock" },
		{ 2, 4, "Standard Stock" },
		{ 3, 4, "Standard Stock" },
		{ 1, 4, "Sniper Stock" },
		{ 2, 4, "Sniper Stock" },
		{ 3, 4, "Sniper Stock" },
		{ 4, 4, "Sniper Stock" },
		{ 4, 4, "Turbocharger" },
		{ 4, 4, "Selectfire" },
		{ 4, 4, "Dual Shell" },
		{ 4, 4, "Skullpiercer" },
		{ 4, 4, "Skullpiercer Elite" },
		{ 4, 4, "Skullpiercer Elite" },
		{ 4, 4, "Disruptor Rounds" },
		{ 4, 4, "Hammerpoint" },
		{ 4, 4, "Double Tap" },
		{ 1, 4, "Graffiti Mod" },
		{ 4, 4, "Splatter Rounds" },
		{ 4, 4, "Quickdraw Holster" },
		{ 4, 4, "Shatter Caps" },
		{ 4, 4, "Kinetic Feeder" },
		{ 4, 4, "Boosted Loader" },
		{ 4, 4, "Gun Shield" },
		{ 4, 4, "Accelerator" },
		{ 1, 4, "Elite Weapon" },
		{ 4, 4, "Graffiti Mod" },
		{ 4, 4, "Executioner" },
		{ 1, 4, "Gun Shield" },
		{ 1, 4, "Selectfire" },
		{ 1, 4, "Anvil Receiver" },
		{ 1, 4, "Skullpiercer" },
		{ 1, 4, "Accelerator" },
		{ 1, 4, "Quickdraw Holster" },
		{ 1, 4, "Dual Shell" },
		{ 1, 4, "Hammerpoint" },
		{ 1, 4, "Disruptor Rounds" },
		{ 1, 4, "Double Tap" },
		{ 1, 4, "Turbocharger" },
		{ 1, 4, "Graffiti Mod" },
		{ 1, 4, "Executioner" },
		{ 2, 4, "Hop-Up Booster" },
		{ 2, 6, "Mobile Respawn" },
		{ 5, 6, "Vault Key" },
		{ 5, 6, "Steel Cut Charm" },
		{ 5, 6, "Treasure Pack" },
		{ 3, 6, "Doubler Flag" },
		{ 4, 6, "Quadrupler Flag" },
		{ 2, 6, "Heat Shield" },
		{ 4, 6, "MRVN Arm" },
		{ 5, 6, "Bridge Keycard" },
		{ 2, 6, "Evac Tower" },
		{ 5, 6, "Respawn Banner" },
		{ 5, 6, "Respawn Banner" },
		{ 5, 0, "Buster Sword" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 5, 6, "Nessie" },
		{ 1, 5, "REV Shell" },
		{ 2, 6, "Blue Materia" },
		{ 1, 6, "Green Materia" },
		{ 4, 6, "Yellow Materia" },
		{ 3, 6, "Purple Materia" },
		{ 5, 6, "Red Materia" },
		{ 2, 6, "Small Evo Cache" },
		{ 4, 6, "Full Evo Cache" },
		{ 3, 6, "Large Evo Cache" },
		{ 1, 6, "Evo Orb" },
		{ 2, 6, "Evo Orb" },
		{ 3, 6, "Evo Orb" },
		{ 4, 6, "Evo Orb" },
		{ 5, 6, "Evo Orb" },
		{ 5, 6, "Hunt" },
		{ 5, 6, "Mythic Bin Key" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 4, 6, "Boost Kit" },
		{ 3, 6, "Boost Kit" },
		{ 3, 6, "Hoverboard" },
		{ 3, 6, "Infinite Ammo Amp" },
		{ 3, 6, "Battery Amp" },
		{ 3, 6, "Overflow Healer Amp" },
		{ 3, 6, "Power Booster Amp" },
		{ 3, 6, "Over Armor Amp" },
		{ 4, 0, "Flatline" },
		{ 4, 4, "Road Rage" },
		{ 4, 4, "Bit Stave Kit" },
		{ 4, 4, "Galvanic Gavel" },
		{ 4, 4, "Redline" },
		{ 5, 6, "Fighter Gear" },
		{ 5, 6, "Fighter Gear" },
		{ 5, 6, "Fighter Gear" },
		{ 5, 6, "Fighter Gear" },
		{ 5, 6, "Fighter Token" },
		{ 5, 4, "Overflow Mag" },
		{ 5, 4, "Headseeker Barrel" },
		{ 5, 4, "Tactical Laser" },
		{ 5, 4, "Agile Stock" },
		{ 5, 4, "Rapid Sniper Stock" },
	}};

	inline auto lookup( int id ) -> const record_t*
	{
		if ( id <= 0 || id >= static_cast<int>( k_records.size( ) ) )
			return nullptr;
		const auto& r = k_records[ static_cast<std::size_t>( id ) ];
		if ( !r.name || !r.name[ 0 ] )
			return nullptr;
		return &r;
	}
}
